README.md, package.json, src/index.ts
@btroncone it looks like you are already working on v2 and perhaps you had this already outlined but I really needed to support a partial state sync. I think this is similar to #4. This pull request introduces a new way of defining keys in a form of:
````js 
localStorageSync([{todos: ['name', 'status'] }, ... ])
````
where the key represents the state key and the value represents an array of properties which should be synced.
The previous format:
````js 
localStorageSync('todos', ... ])
````
should be still supported.
=> Added support for partial state sync

README.md
For some reason, we need to manually specify the type of the meta-reducers, as shown in 
https://github.com/ngrx/platform/issues/170#issuecomment-318031101
Fixes #45
=> Update readme for ngrx 4.0

src/index.ts
Hello!
Thanks for the nice module, I do use this on daily basis :)
I realised a behiviour and realised that the RegEx to test the date string is not enough. Here is a way to reproduce it:
```js
const detectDate = /(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})/;
detectDate.test('foo1111-11-11T11:11:11bar')
```
`Date.parse` could be used as a validator so I replaced that with it.
Cheers!
=> use Date.parse instead of RegEx

README.md
ngrx/platform#270 (landed in store 4.0.3) changed the type signature of the meta reducers array.
This fixes the resulting type conflict with the usage example.
=> Update readme for ngrx store 4.0.3

spec/index_spec.ts, src/index.ts
This fixes the issue #58 .
The state presented on the report is a string instead of an object thus JSON.parse throws an exception.
=> Evaluating if the persisted state is an object

src/index.ts
I have the same issue like this one:
[issue 44](https://github.com/btroncone/ngrx-store-localstorage/issues/44)
I guess this check can help, because if we don`t have a substate we cannot do anything.
This fix solves the problem. Thank you.
=> Add additional check state

README.md
There was a tiny typo in the docs for the `filter` option. I also added a link to lib.dom.d.ts for the Storage interface.
No functionality changes, just documentation update.
=> Fix Typo. Add Storage Interface Reference

README.md, spec/index_spec.ts, src/index.ts
Fixes #70
This should also fix tests runs, which are executed _not_ in the GMT timezone.
=> Introduce flag to globaly turn of date reviving

src/index.ts
Currently rehydrating of feature module state doesn't work if you have keys defined in the root module. With every added module, the rehydration function gets called with the "@ngrx/store/update-reducers" action and syncs the initial state to the localStorage.
This change fixes it for me. On a quick glance it seems to fix the following issues: #75, #72, #64, #44
=> fix rehydrating of feature module state

package.json
Allows using [@ngrx/store](https://github.com/ngrx/platform/) `^5.0.0` as peer dependency.
https://github.com/ngrx/platform/blob/v5.0.0/modules/store/CHANGELOG.md should not introduce any breaking changes related to the functionality.
=> Change peer dependency to @ngrx/store v4 or v5

src/index.ts
If a null is stored in a separate key/value it should be looked upon as a object, not a string.
Otherwise the null will become a string. you're not gonna have a good time :grinning: 
Fix suggested by @RubenVermeulen
=> Null is an object!

package.json, spec/index_spec.ts, src/index.ts
Replaces https://github.com/btroncone/ngrx-store-localstorage/pull/15
It's common for state schemas to change throughout time. For example
```
{
state: {
foo: string;
}
}
```
may become
```
{
state: {
bar: string;
}
}
```
Doing so with rehydrate enabled can break an application. Our new initial state may contain just bar. However the redyrated state contains foo instead. A selector may expect bar to exist and errors when it does not.
Instead of using just the deserialized state from localstorage, merge it with initial state. Thanks to qvantor for a solution to that. However qvantor's pull request did not contain any unit test and the issue is rather murky on what exactly is the problem. The intent of this pull request is to clear up exactly what the problem is and my suggested fix with …
=> Merge initial and rehydrated states

package.json, src/index.ts
Alternative fix for #123
This change gets the project on a better maintained package. lodash.merge is no longer maintained and suffers from a potential security vulnerability. lodash itself would increase the bundle size to an unacceptable level. Switching to deepmerge actually reduces the webpack bundle size by about 10k compared to lodash.merge.
Previously it was decided to avoid deepmerge due to observed issues when used with the project vuex-persist. This seems only to be unwanted array concatenation instead of replacement. It's easy to avoid this using options set to deepmerge, which this PR demonstrates.
Still this is a significant change and we cannot guarantee the behaviour will exactly match lodash.merge. If we decide to go with deepmerge, I recommend releasing a beta release and …
=> Try replacing lodash with deepmerge

README.md, spec/index_spec.ts, src/index.ts
Adds the ability to define a custom reducer for merging the rehydrated storage state with the store. If no merge reducer is specified, defaults to the current deepmerge on `INIT` and `UPDATE` strategy. This shouldn't change any existing behaviour.
Seems like this idea was already proposed in #65 before deepmerge was selected as the default strategy, but it's become pretty obvious that there's no one-size-fits-all solution here.
Resolves issues like #114, #110, #80 and #128 by allowing custom merge reducers to be defined for these use-cases. Resolves issues like #120 by allowing rehydrated state to be updated on any desired action.
See test for an example of a combined merge strategy using both deepmerge and object.assign.
=> Add merge reducer option

CHANGELOG.md, README.md, package.json, src/index.ts
- feat: remove deprecated localStorageSyncAndClean function
- update changelog and bump to version 9.0.0
Changelog updated for #142 and #135.
=> Remove deprecated `localStorageSyncAndClean`, v9 changelog

.editorconfig, README.md, package-lock.json, package.json, spec/index_spec.ts, src/lib/index.ts
This PR allows for more targeted configuration of state, removing the restriction that only top-level data can be stored. For instance, this is now a valid configuration:
```
export function localStorageSyncReducer(
reducer: ActionReducer<any>
): ActionReducer<any> {
return localStorageSync({
keys: [
{
account: [
{ settings: [{ settingsGroup1: ['oneSettingInParticular'] }] },
],
},
]
})(reducer);
}
```
The above configuration would result in a localstorage value under the key `account` that looked like so, ignoring all other values in account, settings, or settingsGroup1:
```
{
"settings": {
"settingsGroup1": {
"oneSettingInParticular": "value of setting"
}
}
}
```
Upgraded TS to 3.9.7
Added .editorconfig
=> Infinite depth configuration

.circleci/config.yml
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Issue Number: #192
Manually add github ssh keys to the `known_hosts` file before running semantic release
Based on the Circle CI docs: https://circleci.com/docs/2.0/gh-bb-integration/#establishing-the-authenticity-of-an-ssh-host
=> ci: manually add github ssh keys to known_hosts

projects/lib/src/lib/index.ts
Check if storage is undefined before using removeItem
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Using Angular Universal and the removeOnUndefined option throws the error:
```
TypeError: Cannot read property 'removeItem' of undefined
```
Avoid error.
=> fix: removeOnUndefined option using Angular Universal

.gitignore, package-lock.json, package.json, projects/lib/ng-package.json, projects/lib/package.json, projects/lib/src/lib/index.ts, spec/index_spec.ts
Bump min versions of Angular and NgRx packages to v13
Support Angular and NgRx 13
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
Issue Number: #206
=> feat: support Angular 13

projects/lib/src/lib/index.ts, spec/index.spec.ts
- Reverts the date parsing changes from #274
- Adds start of line check to date reviver regex to fix #138
1. This library has been around for a long time now. I think it's important to minimize changes that may cause applications to break unexpectedly. Even though there is #282 to fix the number parsing issue specifically, I think it's better to just revert to the previous ISO date format regex detection to be on the safe side.
2. If someone wants custom date reviver behavior they can use the `reviver` config to achieve that.
3. The default `JSON.stringify()` behavior creates an [ISO string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON) which this implementation handles
4. A similar change to use `Date.parse()` was introduced way back in …
=> Revert date parse change, add start of line check to regex
